CDPD-9392. Use 7.1.1.0 builds part 4
hive.classifier was dropped because CDP Spark 2.4 does not use it either. With the classifier the bellow java.lang.NoClassDefFoundError is coming up on -SNAPSHOT builds:
java.lang.NoClassDefFoundError: org/apache/orc/impl/HadoopShims
        at org.apache.orc.OrcFile$WriterOptions.<init>(OrcFile.java:467)
        at org.apache.orc.OrcFile.writerOptions(OrcFile.java:847)
        at org.apache.orc.mapred.OrcOutputFormat.buildOptions(OrcOutputFormat.java:50)
        at org.apache.spark.sql.execution.datasources.orc.OrcOutputWriter.<init>(OrcOutputWriter.scala:46)
        at org.apache.spark.sql.execution.datasources.orc.OrcFileFormat$$anon$1.newInstance(OrcFileFormat.scala:120)
        at org.apache.spark.sql.execution.datasources.SingleDirectoryDataWriter.newOutputWriter(FileFormatDataWriter.scala:126)
        at org.apache.spark.sql.execution.datasources.SingleDirectoryDataWriter.<init>(FileFormatDataWriter.scala:111)
        at org.apache.spark.sql.execution.datasources.FileFormatWriter$.executeTask(FileFormatWriter.scala:264)
        at org.apache.spark.sql.execution.datasources.FileFormatWriter$.$anonfun$write$15(FileFormatWriter.scala:205)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
        at org.apache.spark.scheduler.Task.run(Task.scala:127)
        at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:444)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:447)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.apache.orc.impl.HadoopShims
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 17 more
The reason for the exception is very likely in orc-core -SNAPSHOT artifacts:
[WARNING] The POM for org.apache.orc:orc-core:jar:1.5.1.7.1.1.0-SNAPSHOT is invalid, transitive dependencies (if any) will not be available: 1 problem was encountered while building the effective model for org.apache.orc:orc-core:1.5.1.7.1.1.0-SNAPSHOT
[ERROR] 'dependencies.dependency.version' for org.threeten:threeten-extra:jar is missing. @
which results that orc-shim dependency of orc-core is missing from the classpath.
Please note that only -SNAPSHOT artifact has this issue.

Without the classifier the “full” hive-exec artifact is used on the classpath that also contains the missing class.

Change-Id: I3d8ba80f10593d78b6d4c63097d670d8d686d94e